{
  "name": "Error",
  "request": {},
  "response": {},
  "body": {
    "statusCode": 400,
    "error": "Bad Request",
    "message": "[illegal_argument_exception\n\tRoot causes:\n\t\tillegal_argument_exception: data_description.time_field may not be used in the analysis_config]: data_description.time_field may not be used in the analysis_config",
    "attributes": {
      "body": {
        "error": {
          "root_cause": [
            {
              "type": "illegal_argument_exception",
              "reason": "data_description.time_field may not be used in the analysis_config"
            }
          ],
          "type": "illegal_argument_exception",
          "reason": "data_description.time_field may not be used in the analysis_config"
        },
        "status": 400
      }
    }
  }
}